# Generated by Django 6.0.4 on 2026-04-19 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('atendente', 'Atendente'), ('analista', 'Analista'), ('gestor', 'Gestor'), ('operacional', 'Operacional'), ('admin', 'Administrador')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('elogio', 'Elogio'), ('reclamacao', 'Reclamação'), ('sugestao', 'Sugestão')], max_length=20)),
                ('descricao', models.TextField()),
                ('prioridade', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('analise', 'Em análise'), ('respondido', 'Respondido'), ('concluido', 'Concluído')], default='aberto', max_length=20)),
                ('resposta', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='feedbacks/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servico')),
            ],
        ),
    ]
